apiVersion : apps/v1
kind : Deployment
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Values.app.namespace }}
    labels:
       app: {{ .Release.Name }}-ex-dep
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}
        spec:
            containers:
              - name : {{ .Release.Name }}-dep
                image: {{ .Values.container.image }}                              
                ports:
                  - containerPort: {{ .Values.server.port }}        
                env:               
                 
                - name: server.port
                  value: "{{ .Values.server.port }}"
                      
                - name: db_dialect
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_dialect       
                      
                - name: db_driver_class
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_driver_class       
                      
                - name: db_provider_class
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_provider_class   
                
                - name: db_url
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_url
                
                - name: db_username
                  valueFrom:                    
                    secretKeyRef:
                      name: message-secret
                      key: username                      
                
                - name: db_password
                  valueFrom:                    
                    secretKeyRef:
                      name: message-secret
                      key: password
                
                - name: db_current_session_context_class
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_current_session_context_class            
                
                - name: db_timeout
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_timeout
                
                - name: db_acquireRetryAttempts
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_acquireRetryAttempts            
                
                - name: db_acquireRetryDelay
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_acquireRetryDelay
                
                - name: db_breakAfterAcquireFailure
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_breakAfterAcquireFailure            
                
                - name: db_maxConnectionAge
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_maxConnectionAge
                
                - name: db_maxIdleTime
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_maxIdleTime           
                
                - name: db_maxIdleTimeExcessConnections
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_maxIdleTimeExcessConnections
                
                - name: db_idleConnectionTestPeriod
                  valueFrom:
                    configMapKeyRef:
                      name: message-cm  
                      key: db_idleConnectionTestPeriod                    
                
                volumeMounts:
                - name: configapp
                  mountPath: "/usr/local/service/configapp"
                  readOnly: true       
                  
                volumeMounts:
                - name: logforjconfig
                  mountPath: "/usr/local/service/config"
                  readOnly: true            
                  
            volumes:
              - name: configapp
                configMap:
                  name: log-message-cm
                  items:
                  - key: "appdataoperationconfig"    
                    path: "application.properties"                        
            volumes:
              - name: logforjconfig
                configMap:
                  name: log-message-cm
                  items:
                  - key: "loggerconfig"    
                    path: "log4j2.properties" 

