apiVersion: v1
kind: Secret
metadata:
  name: message-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: YWRtaW4=


  
        
                        