# migration/migration-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job

spec:
  template:
    spec:
      containers:
        - name: flyway
          image: boxfuse/flyway:5.2.4
          command: ["flyway", "-outOfOrder=true", "-validateOnMigrate=false", "migrate"]                     
          env:
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: 'true'
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap  
                  key: db_url
            - name: FLYWAY_USER
              valueFrom:                    
                secretKeyRef:
                  name: migration-secret
                  key: username 
            - name: FLYWAY_PASSWORD
              valueFrom:                    
                secretKeyRef:
                  name: migration-secret
                  key: password
            - name: FLYWAY_PLACEHOLDER_REPLACEMENT
              value: "true"
            - name: FLYWAY_PLACEHOLDERS_USERNAME
              valueFrom:                    
                secretKeyRef:
                  name: migration-secret
                  key: username
            - name: FLYWAY_PLACEHOLDERS_PASSWORD
              valueFrom:                    
                secretKeyRef:
                  name: migration-secret
                  key: password
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          configMap:
            name: postgres-configmap
      restartPolicy: Never