{
 "title": "Common homework",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Latency by HTTP methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency by GET method ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": " histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\"}[5m])))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "  histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\"}[5m])))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": " histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\"}[5m])))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "  histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\"}[5m])))",
     "legendFormat": "Quantile max"
    }
   ]
  },
  {
   "title": "Latency by POST method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\"}[5m])))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\"}[5m])))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\"}[5m])))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\"}[5m])))",
     "legendFormat": "Quantile max"
    }
   ]
  },
  {
   "title": "Latency by PUT method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PUT\"}[5m])))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": " histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PUT\"}[5m])))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": " histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PUT\"}[5m])))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": " histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"PUT\"}[5m])))",
     "legendFormat": "Quantile max"
    }
   ]
  },
  { "title": "RPS by API methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": " RPS by GET method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\", uri=~\"/*\"}[1m])",
     "legendFormat": "exuser"
    }
   ]
  },
  {
   "title": "RPS by POST method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"POST\"}[1m])",
     "legendFormat": "exuser"
    }
   ]
  },
  {
   "title": "RPS by PUT method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"PUT\"}[1m])",
     "legendFormat": "exuser"
    }
   ]
  },
  { "title": "Error Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Error 5... by API method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{status=~\"5.*\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Requested",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_resource_requests{resource=\"memory\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\"})/ sum (kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\"})/sum (kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSql BD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"postgres\"})"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"postgres\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"postgres\"})"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Rate of Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(pg_stat_activity_count{datname=~\"postgres\", application_name!=\"PostgreSQL JDBC Driver\", container=\"prometheus-postgres-exporter\", state=~\"idle\"}[2m])",
     "legendFormat": "idle"
    },
    {
     "expr": "rate(pg_stat_activity_count{datname=~\"postgres\", application_name=\"PostgreSQL JDBC Driver\", container=\"prometheus-postgres-exporter\", state=~\"idle in transaction\"}[2m])",
     "legendFormat": "idle in transaction"
    },
    {
     "expr": "rate(pg_stat_activity_count{datname=~\"postgres\", application_name=\"PostgreSQL JDBC Driver\", container=\"prometheus-postgres-exporter\", state=~\"idle in transaction (aborted)\"}[2m])",
     "legendFormat": "idle in transaction aborted"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"postgres\"} != 0",
     "legendFormat": "postgres"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"postgres\"} != 0",
     "legendFormat": "postgres"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 15, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{ datname=~\"postgres\"}[5m])",
     "legendFormat": "postgres commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{ datname=~\"postgres\"}[5m])",
     "legendFormat": "postgres rollback"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"postgres\", mode=~\"accesssharelock\"} != 0",
     "legendFormat": "postgres,accesssharelock"
    },
    {
     "expr": "pg_locks_count{datname=~\"postgres\", mode=~\"rowexclusivelock\"} != 0",
     "legendFormat": "postgres, rowexclusivelock"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"postgres\"} != 0",
     "legendFormat": "postgres"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"postgres\"} != 0",
     "legendFormat": "postgres"
    }
   ]
  },
  { "title": "System extended", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  }
 ]
}