apiVersion : apps/v1
kind : Deployment
metadata:
    name: {{ .Release.Name }}
    labels:
       app: {{ .Release.Name }}-ex-dep
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            project: {{ .Release.Name }}
    template:
        metadata:
            labels:
                project: {{ .Release.Name }}
        spec:
            containers:
              - name : {{ .Release.Name }}-dep
                image: {{ .Values.container.image }}                              
                ports:
                  - containerPort: 8000          	

    