apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-service
    labels:
        env : prod
        owner: AlexIvanov
spec:
    selector:
        project: {{ .Release.Name }}
    ports:         
      - name      : oper-app-list
        protocol  : TCP
        port      : 80
        targetPort: 8000      
    type: LoadBalancer   


  
        
                        