container:
  image: sergey789/userprofile:v2
  
replicaCount: 1  

server:
  port: 8080
    
db:
  url: jdbc:postgresql://bduserprofile-postgresql.authprovider:5434/postgres
  
port:
  name: user-port  
  
secret:
  jwt: jwtsecret  
 

