container:
  image: sergey789/order:v1.0
  
replicaCount: 1  

server:
  port: 8085
    
db:
  url: jdbc:postgresql://bdorder-postgresql.order-ns:5434/postgres
  
port:
  name: order-port    
  
app:
  namespace: order-ns
  
ingress:
  namespace: ingress-ns
 
serive:
  message:
    url: messagews.message-ns.svc.cluster.local
    port: 80

 

