apiVersion: v1
name: orderwr
description: Deploy service orderwr 
type: application
version: 0.0.1
appVersion: "1.0.0"

keywords:
  - kubernetes  
  - orderwr
  - ingress
  - helm
  
maintainers:
  - name: AlexIvanov
  